### PR TITLE
hermit: Allow filtering output

### PR DESCRIPTION
**Pull request by marcusolsson**
Adds some filtering options to the ls subcommand:

`hermit ls -filter "min_age=5m,status=running"` lists all tasks that have been running for longer than 5 minutes

### CODE REVIEW

**Comment by marcusolsson** [comment]
Maybe. I guess the question is how much we would gain from it. For a large number of tasks, the `ls` command is a bit slow. Server side filtering could help but wouldn't know until we did some profiling to know where the bottleneck is. I'll do some digging, but for now I think client side filtering is quite simple and clean way to do it.

**Comment by keis** [comment]
I'm not to worried about the performance of this right now as we're only operating on the active tasks which is a pretty small set. Tuning for data sent / processing in client vs server is a bit tricky and should really only be done, as you say, after profiling things seriously.

But I was thinking this could be useful for other code consuming the API directly. But I guess there's nothing stopping us from adding that later on if we find the need.

**Comment by marcusolsson** [comment]
Right, I think it would be wise to hold off on adding more stuff to the current server API, and use hermit as a test bed until we feel confident enough about how we what to use it.

**Comment by alde** [comment]
[LGTM](https://lgtm.in/i/WVCX4BMjq)

**Pull request merged**
