### PR TITLE
Add URL Prefix support for DCOS package

### PR DESCRIPTION
**Pull request by gisjedi**
I've added support in the config to specify a custom PathPrefix in the router to shim the URL. This is specifically to support DCOS Admin Router (ref #164), but can be used in any reverse proxy scenario where eremetic lives at a relative path other than `/`.

As a part of this, it was necessary to update the static assets. JavaScript files now use the `EREMETIC_URL_PREFIX` var via template injection to make ajax calls. All assets URLs are also updated via template injection using the `URLPrefix` map key.

This is my first time at a PR against a golang project, so please let me know if there are any best practices I did not follow. I did run gofmt on all the files.

The images have also been updated, as DCOS package previews didn't look great with transparencies.

### CODE REVIEW

**Comment by keis** [comment]
I'm not sure how the admin router works but in general with forward proxys the prefix is stripped before sending to the upstream. So while our links should say PREFIX/foo/bar the routing should still only look for /for/bar. But maybe that's not the case here.

Otherwise LGTM

**Comment by gisjedi** [comment]
@keis The primary issue here is with the static assets all being referenced at `/static` absolute URLs. Without a shim to rewrite all of them to the proxied path all images, javascript and css would result in 404s. I think you are correct that the actual service handlers can still listen behind the proxy at a root context, but the service certainly needs to advertise itself at the proxied location (location headers, etc.).

I'm going to add some additional test coverage and then if you don't have any other requests I think it'll be ready.

**Comment by keis** [comment]
That depends on how the reverse proxy is configured but regardless we need to prefix the urls we are advertising. In my experience stripping the prefix in the proxy is the more common scenario but lets just go with what the admin router expects for now.

I can see the value in supporting both if the need arises by splitting the config (eg URLPrefix and AdvertiseURLPrefix)

**Comment by gisjedi** [comment]
After further testing behind DCOS Admin Router, it appears we do only need the advertisted URL prefix. I have removed the subrouter path prefix, leaving just the advertising of the prefix. Let me know if you forsee any other issues. If not, I'm satisfied with this.

As far as the DCOS package itself, I'll need a new release with these updates in a versioned tag on `alde/eremetic` Docker image. What is your current release cycle?

**Comment by keis** [comment]
Thanks @gisjedi 

I'll give it a quick test and then look at tagging a new release

**Pull request merged**
