### PR TITLE
Return empty array instead of `null` when tasks list is empty

### PR DESCRIPTION
**Pull request by sheepkiller**
go lint doesn't like it, but it's nicer for clients

### CODE REVIEW

**Comment by sheepkiller** [comment]
Hi,

Another option is to return "make([]*types.EremeticTask, 0)" in  `ListRunningTasks()` if database backend returns nothing

**Comment by alde** [comment]
You should also be able to do

```
tasks := []*types.EremeticTask{}
```

I think, which makes go lint happy

I did this in https://github.com/alde/physical/blob/master/physical.go#L89

**Comment by sheepkiller** [comment]
hi @alde,

nice. thanks you !

**Comment by keis** [comment]
[LGTM](http://lgtm.in/i/y7HZxMflq)

**Pull request merged**
