### PR TITLE
Expose eremetic version

### LINKED ISSUE #103: Report eremetic version in api & gui
To be able to at a glance tell what version you are running

### PR DESCRIPTION
**Pull request by alde**
Add API-endpoint `/version`
Add version to GUI

fixes #103

### CODE REVIEW

**Comment by keis** [comment]
using a ajax request to show to version is a bit excessive. why not include it in the first output? it's not like it's likely to change runtime or anything

**Comment by alde** [comment]
Mostly because it required moving more code around. I did it that way first, but felt the changes became unnecessarily big.

Can do it that way instead though

**Comment by keis** [comment]
I guess you could pull the version from the module instead of carrying it on the config. if that makes things easier

**Comment by alde** [comment]
I tried putting the version.go in a version package, but for some reason the makefile magic didn't want to work then

**Comment by keis** [comment]
[LGTM](http://lgtm.in/i/wCNwjlJ8q)

**Pull request merged**
