### PR TITLE
Support adding uris to command info

### PR DESCRIPTION
**Pull request by keis**
The extract flag is set based on the same list of suffixes as used by
marathon

### CODE REVIEW

**Comment by alde** [comment]
I'm skeptical to the name "uri", it is very unclear what it means without understanding the mesos api.

**Comment by keis** [comment]
I'm not super happy with it either but could not come up with anything better so I just used what it's called in the mesos protobuf and marathon apis, "uris"

**Comment by alde** [comment]
Fair enough. Please add it to the readme then at least. :)

**Comment by keis** [comment]
Good point. updated. Also made sure we got some sweet syntax highlighting in the readme going

**Comment by alde** [comment]
[LGTM](http://lgtm.in/i/2ZQAvK3Np)

**Pull request merged**
