### PR TITLE
Add task queued state

### LINKED ISSUE #110: Add a `TASK_QUEUED` state
Hi,

I'm using eremetic to launch jobs on an autoscale group of slaves, and sometimes. jobs are waiting in the queue for a while. Currently `TASK_STAGING` state is not precise enough, since status is set when the task is created in the queue, not launched on mesos.
Here's what I propose:
- When `NewEremeticTask` is called, set the task status to `TASK_QUEUED`
- When `createTaskInfo` is call, status is updated to add `TASK_STAGING` 
- If task failed and is elligible for a retry, `StatusUpdate` will update status to `TASK_QUEUED`

thanks

### PR DESCRIPTION
**Pull request by keis**
Shuffling code around to allow for custom task state. still need to actually and the queue state.

Fixes #110

### CODE REVIEW

**Comment by alde** [comment]
thank you

**Comment by alde** [comment]
LGTM

**Comment by keis** [comment]
Want to give this a test spin before we merge

**Comment by keis** [comment]
small update to add staging state when we accept the offer as we do not seem to get that as a status update from mesos.

@alde Could you throw another goats eye at this?

**Comment by alde** [comment]
lgtm

Right on!

**Pull request merged**
