### PR TITLE
Task attribute constraints

### LINKED ISSUE #78: Specify attributes when creating tasks
Super useful for splitting clusters of resources or for running commands against specific hosts.

Attributes are key/value pairs can be applied to slaves. See:
http://mesos.apache.org/documentation/latest/configuration/

### PR DESCRIPTION
**Pull request by keis**
Fixes #78 
Rebase and squash of #88

### CODE REVIEW

**Comment by keis** [comment]
I'm cool with the state of this. WDYT @alde ?

**Comment by alde** [comment]
lgtm

I've also taken out the Port in my branch, but i named it AgentPort along with AgentIP, so I'm unsure which name we should use.

**Comment by keis** [comment]
I like AgentPort more, it's less ambigous

**Comment by alde** [comment]
lgtm!

**Pull request merged**
